# Generated by Django 2.1.2 on 2018-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIVILITE', models.CharField(max_length=3)),
                ('NOM', models.CharField(max_length=255)),
                ('PRENOM', models.CharField(max_length=255)),
                ('NUM_TEL', models.CharField(max_length=10)),
                ('ADR_MAIL', models.CharField(max_length=255)),
            ],
        ),
    ]
