# Generated by Django 2.1.2 on 2018-11-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
