# Generated by Django 2.1.2 on 2018-11-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0003_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='CLIENT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe3.Client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='TOTAL',
            field=models.IntegerField(default=0),
        ),
    ]
