# Generated by Django 2.1.2 on 2018-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0004_auto_20181118_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_VOIRIE', models.CharField(max_length=10)),
                ('VOIRIE', models.CharField(max_length=30)),
                ('NOM_RUE', models.CharField(max_length=255)),
                ('CODE_P', models.CharField(max_length=5)),
                ('VILLE', models.CharField(max_length=30)),
                ('PAYS', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_CAT', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDP_COMPTE', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUT', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_LIVRAISON', models.CharField(max_length=30)),
                ('TRANSPORTEUR', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_PRODUIT', models.CharField(max_length=30)),
                ('DESCRIPTION', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_ROLE', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='TOTAL',
        ),
    ]
