# Generated by Django 2.1.2 on 2018-12-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0006_auto_20181121_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='POID_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='QUANTITEE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='TAILLE_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
    ]
