# Generated by Django 2.1.2 on 2018-12-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0007_auto_20181227_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='produit_commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QT_PRODUIT', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='newtable01',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='QUANTITEE',
            new_name='QUANTITEE_STOCK',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='TAILLE_PRODUIT',
        ),
        migrations.AddField(
            model_name='livraison',
            name='DUREE_LIV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='HAUTEUR_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='LARGEUR_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='PRIX_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='produit_commande',
            name='Commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe3.Commande'),
        ),
        migrations.AddField(
            model_name='produit_commande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe3.Produit'),
        ),
    ]
