# Generated by Django 2.1.2 on 2018-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0008_auto_20181229_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='POID_PRODUIT',
            field=models.IntegerField(default=0),
        ),
    ]
