# Generated by Django 2.1.2 on 2018-12-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0009_auto_20181229_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='HAUTEUR_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='LARGEUR_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='PRIX_PRODUIT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
