# Generated by Django 2.1.2 on 2018-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0011_auto_20181229_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='USER_SESSION',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
