# Generated by Django 2.1.2 on 2018-12-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe3', '0012_client_user_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresse',
            old_name='NOM_RUE',
            new_name='ADRESSE',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='N_VOIRIE',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='VOIRIE',
        ),
    ]
